1.vim: update signify, 2.update color_test 3.update some file mode

diff --git a/.bin/colors_test b/.bin/colors_test
--- a/.bin/colors_test
+++ b/.bin/colors_test
@@ -39,3 +39,18 @@ echo -e "\e[0;34mCOLOR_BLUE\t\e[1;34mCOLOR_BOLD_BLUE"
 echo -e "\e[0;35mCOLOR_PURPLE\t\e[1;35mCOLOR_BOLD_PURPLE"
 echo -e "\e[0;36mCOLOR_CYAN\t\e[1;36mCOLOR_BOLD_CYAN"
 echo -e "\e[0;37mCOLOR_WHITE\t\e[1;37mCOLOR_BOLD_WHITE"
+
+echo -e "\e[0m"
+echo "NCURSES:"
+if ! hash tput 2>/dev/null; then
+    echo "Cannot find the 'tput' program." \
+        'You might find it in one of the ncurses packages.' >&2
+else
+    for i in {0..255}; do
+        tput setab $i && echo -n " $i "
+    done
+    tput sgr0
+    echo
+fi
+
+
