x: add -e/--here option

diff --git a/.bin/x b/.bin/x
--- a/.bin/x
+++ b/.bin/x
@@ -10,10 +10,11 @@ if (( $# == 0 )) || [[ "$1" == "-h" ]] || [[ "$1" == "--help" ]]; then
     cat <<EOF
 Extract or compress archive files
 Usage: x [-option] [file ...]
-Default: Extract archive file
+Default: Extract archive file to new archive-file-name directory
 Options:
     -l, --list      List archive files' name.
-    -p, --plain     Plain extract files
+    -p, --plain     Plain extract files to current directory
+    -e, --here      Extract files to current directory
     -c, --compress  Compress files/directories to archive file
                     x -c <archive-name> <files>
     -i, --install   Install linux package to /
@@ -26,6 +27,7 @@ local list_archive
 local plain_extract
 list_archive=0
 plain_extract=0
+here_extract=0
 
 # compress
 if [[ "$1" == "-c" ]] || [[ "$1" == "--compress" ]]; then
@@ -83,6 +85,12 @@ if [[ "$1" == "-p" ]] || [[ "$1" == "--plain" ]]; then
     shift
 fi
 
+# current dir extract
+if [[ "$1" == "-e" ]] || [[ "$1" == "--here" ]]; then
+    here_extract=1
+    shift
+fi
+
 while (( $# > 0 )); do
     if [[ ! -f "$1" ]]; then
         echo "extract: '$1' is not a valid file" >&2
@@ -100,22 +108,26 @@ while (( $# > 0 )); do
         esac
     else
         # extract
-        case "$1" in
-            (*.tar.gz|*.tar.bz2|*.tar.xz|*.tar.zma) extract_dir="${1:t:r:r}" ;;
-            (*) extract_dir="${1:t:r}" ;;
-        esac
-        # exist ?
-        if [[ -d $extract_dir ]]; then
-            echo -n "'$extract_dir' is exist, remove and replace it? [yN] "
-            read -rs -k 1 answer
-            [[ -n "$answer" ]] && echo
-            if [[ "$answer" != "y" ]]; then
-                echo "Abort extract!" >&2
-                return
+        if [[ "$here_extract" == "0" ]]; then
+            case "$1" in
+                (*.tar.gz|*.tar.bz2|*.tar.xz|*.tar.zma) extract_dir="${1:t:r:r}" ;;
+                (*) extract_dir="${1:t:r}" ;;
+            esac
+            # exist ?
+            if [[ -d $extract_dir ]]; then
+                echo -n "'$extract_dir' is exist, remove and replace it? [yN] "
+                read -rs -k 1 answer
+                [[ -n "$answer" ]] && echo
+                if [[ "$answer" != "y" ]]; then
+                    echo "Abort extract!" >&2
+                    return
+                fi
+                rm -rf "$extract_dir"
             fi
-            rm -rf "$extract_dir"
+            mkdir "$extract_dir"
+        else
+            extract_dir='./'
         fi
-        mkdir "$extract_dir"
         case "$1" in
             (*.tar.gz|*.tgz) tar zxvf "$1" -C $extract_dir ;;
             (*.tar.bz2|*.tbz|*.tbz2) tar xvjf "$1" -C $extract_dir ;;
@@ -143,45 +155,47 @@ while (( $# > 0 )); do
                 echo "extract: '$1' cannot be extracted" >&2
             ;;
         esac
-        rmdir --ignore-fail-on-non-empty "$extract_dir"
 
-        if [[ -d "$extract_dir" ]]; then
-            if [[ "$plain_extract" == "1" ]]; then
-                plain_extract_dir=$extract_dir
-                while true; do
-                    extract_sub_dir=$(ls -A $plain_extract_dir)
-                    sub_dir_files_num=$(wc -l <<< $extract_sub_dir)
-                    if [[ "$sub_dir_files_num" != "1" ]]; then
-                        break
-                    fi
-                    if [[ ! -d "$plain_extract_dir/$extract_sub_dir" ]]; then
-                        break
-                    fi
-                    plain_extract_dir="$plain_extract_dir/$extract_sub_dir"
-                done
-                setopt NULL_GLOB
-                mv "$plain_extract_dir"/{.,}* ./
-                unsetopt NULL_GLOB
-                find "$extract_dir" -type d -empty -delete
-            else
-                # remove double dir
-                extract_sub_dir=$(ls -A $extract_dir)
-                sub_dir_files_num=$(wc -l <<< $extract_sub_dir)
-                if [[ "$sub_dir_files_num" == "1" ]]; then
-                    if [[ -e "$extract_sub_dir" && "$extract_sub_dir" != "$extract_dir" ]]; then
-                        echo -n "'$extract_sub_dir' is exist, remove and replace it? [yN] "
-                        read -rs -k 1 answer
-                        [[ -n "$answer" ]] && echo
-                        if [[ "$answer" != "y" ]]; then
-                            echo "Abort triming extracted directory!" >&2
-                            return
+        if [[ "$here_extract" == "0" ]]; then
+            rmdir --ignore-fail-on-non-empty "$extract_dir"
+            if [[ -d "$extract_dir" ]]; then
+                if [[ "$plain_extract" == "1" ]]; then
+                    plain_extract_dir=$extract_dir
+                    while true; do
+                        extract_sub_dir=$(ls -A $plain_extract_dir)
+                        sub_dir_files_num=$(wc -l <<< $extract_sub_dir)
+                        if [[ "$sub_dir_files_num" != "1" ]]; then
+                            break
                         fi
-                        rm -rf "$extract_sub_dir"
+                        if [[ ! -d "$plain_extract_dir/$extract_sub_dir" ]]; then
+                            break
+                        fi
+                        plain_extract_dir="$plain_extract_dir/$extract_sub_dir"
+                    done
+                    setopt NULL_GLOB
+                    mv "$plain_extract_dir"/{.,}* ./
+                    unsetopt NULL_GLOB
+                    find "$extract_dir" -type d -empty -delete
+                else
+                    # remove double dir
+                    extract_sub_dir=$(ls -A $extract_dir)
+                    sub_dir_files_num=$(wc -l <<< $extract_sub_dir)
+                    if [[ "$sub_dir_files_num" == "1" ]]; then
+                        if [[ -e "$extract_sub_dir" && "$extract_sub_dir" != "$extract_dir" ]]; then
+                            echo -n "'$extract_sub_dir' is exist, remove and replace it? [yN] "
+                            read -rs -k 1 answer
+                            [[ -n "$answer" ]] && echo
+                            if [[ "$answer" != "y" ]]; then
+                                echo "Abort triming extracted directory!" >&2
+                                return
+                            fi
+                            rm -rf "$extract_sub_dir"
+                        fi
+                        rm -rf "${extract_sub_dir}.$$"
+                        mv "$extract_dir/$extract_sub_dir" "${extract_sub_dir}.$$"
+                        rmdir --ignore-fail-on-non-empty "$extract_dir"
+                        mv "${extract_sub_dir}.$$" $extract_sub_dir
                     fi
-                    rm -rf "${extract_sub_dir}.$$"
-                    mv "$extract_dir/$extract_sub_dir" "${extract_sub_dir}.$$"
-                    rmdir --ignore-fail-on-non-empty "$extract_dir"
-                    mv "${extract_sub_dir}.$$" $extract_sub_dir
                 fi
             fi
         fi
