x: install add dir support

diff --git a/.bin/x b/.bin/x
--- a/.bin/x
+++ b/.bin/x
@@ -43,23 +43,29 @@ fi
 # install
 if [[ "$1" == "-i" ]] || [[ "$1" == "--install" ]]; then
     shift
-    while (( $# > 0 )); do
-        if [[ ! -f "$1" ]]; then
-            echo "extract: '$1' is not a valid file" >&2
-            shift
-            continue
-        fi
-        # install
-        case "$1" in
-            (*.tar.gz|*.tgz)         sudo tar zxvf          "$1" -C / ;;
-            (*.tar.bz2|*.tbz|*.tbz2) sudo tar xvjf          "$1" -C / ;;
-            (*.tar.xz|*.txz)         sudo tar --xz -xvf     "$1" -C / ;;
-            (*.tar.zma|*.tlz)        sudo tar --lzma -xvf   "$1" -C / ;;
-            (*.tar)                  sudo tar xvf           "$1" -C / ;;
-            (*) echo "extract: '$1' cannot be extracted" >&2 ;;
-        esac
-        shift
-    done
+    if [[ ! -f "$1" ]]; then
+        echo "extract: '$1' is not a valid file" >&2
+        exit 1
+    fi
+    if [[ -d "$2" ]]; then
+        extract_dir="$2"
+    elif [[ -z "$2" ]]; then
+        extract_dir="/"
+    else
+        echo "extract: '$2' is not a valid directory" >&2
+        exit 1
+    fi
+    # install
+    echo "Install '$1' to '$extract_dir' ..."
+    case "$1" in
+        (*.tar.gz|*.tgz)         sudo tar zxvf        "$1" -C "$extract_dir" ;;
+        (*.tar.bz2|*.tbz|*.tbz2) sudo tar xvjf        "$1" -C "$extract_dir" ;;
+        (*.tar.xz|*.txz)         sudo tar --xz -xvf   "$1" -C "$extract_dir" ;;
+        (*.tar.zma|*.tlz)        sudo tar --lzma -xvf "$1" -C "$extract_dir" ;;
+        (*.tar)                  sudo tar xvf         "$1" -C "$extract_dir" ;;
+        (*) echo "extract: '$1' cannot be extracted" >&2 ;;
+    esac
+    shift
     exit 0
 fi
 
